apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Pratiks-96/game-app.git'
    targetRevision: main
    path: helm/game-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
